# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file_transfer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'file_transfer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66ile_transfer.proto\x12\x0c\x66iletransfer\"T\n\rUploadRequest\x12*\n\x08metadata\x18\x01 \x01(\x0b\x32\x16.filetransfer.MetaDataH\x00\x12\x0f\n\x05\x63hunk\x18\x02 \x01(\x0cH\x00\x42\x06\n\x04\x64\x61ta\"\x1c\n\x08MetaData\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"2\n\x0eUploadResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32Y\n\x0c\x46ileTransfer\x12I\n\nUploadFile\x12\x1b.filetransfer.UploadRequest\x1a\x1c.filetransfer.UploadResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_transfer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADREQUEST']._serialized_start=37
  _globals['_UPLOADREQUEST']._serialized_end=121
  _globals['_METADATA']._serialized_start=123
  _globals['_METADATA']._serialized_end=151
  _globals['_UPLOADRESPONSE']._serialized_start=153
  _globals['_UPLOADRESPONSE']._serialized_end=203
  _globals['_FILETRANSFER']._serialized_start=205
  _globals['_FILETRANSFER']._serialized_end=294
# @@protoc_insertion_point(module_scope)
